lz4_compress-objs    := lz4.o
lz4_hc_compress-objs := lz4hc.o

obj-$(CONFIG_LZ4_COMPRESS)    += lz4_compress.o
obj-$(CONFIG_LZ4_HC_COMPRESS) += lz4_hc_compress.o
obj-$(CONFIG_LZ4_DECOMPRESS)  += lz4_decompress.o

