application: pdk-docs
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  static_files: online-pdk/index.html
  upload: online-pdk/index.html

- url: /(.*)
  static_files: online-pdk/\1
  upload: online-pdk/.*
